# Matematiksel İşlem Uygulamaları

In [1]:
import numpy as np
import numpy.random as rd

In [2]:
array1 = np.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

In [3]:
array2 = np.linspace(6,10,6).astype("int")
array2

array([ 6,  6,  7,  8,  9, 10])

In [4]:
a1 = array1.reshape(3,2)
a1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
a2 = array2.reshape(3,2)
a2

array([[ 6,  6],
       [ 7,  8],
       [ 9, 10]])

In [14]:
a1 - 3 

array([[-3, -2],
       [-1,  0],
       [ 1,  2]])

In [20]:
#Toplama işlemini uygulayalım:
a1 + a2

array([[ 6,  7],
       [ 9, 11],
       [13, 15]])

In [21]:
#Çıkarma işlemini uygulayalım:
a1 - a2

array([[-6, -5],
       [-5, -5],
       [-5, -5]])

In [23]:
#Çarpma işlemini uygulayalım:
a1 * a2

array([[ 0,  6],
       [14, 24],
       [36, 50]])

In [25]:
#Bölme işlemini uygulayalım:
1 / a2

array([[0.16666667, 0.16666667],
       [0.14285714, 0.125     ],
       [0.11111111, 0.1       ]])

In [27]:
#Üs alalım:
a1 ** 3

array([[  0,   1],
       [  8,  27],
       [ 64, 125]], dtype=int32)

In [28]:
#Sabit sayı ile çarpalım:
a1 * 5

array([[ 0,  5],
       [10, 15],
       [20, 25]])