In [1]:
import numpy as np

In [2]:
array = np.arange(15)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
#İlk değeri bulalım:
array[0]

0

In [4]:
#Son değeri bulalım:
array[-1]

14

In [5]:
#Belirli bir değer aralığını bulalım:
array[4:11]

array([ 4,  5,  6,  7,  8,  9, 10])

In [6]:
array[:9:2]

array([0, 2, 4, 6, 8])

In [7]:
array[:5] = 11
array

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

COPY METHODU:

In [8]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
kopya_array = array[:5].copy()
kopya_array

array([0, 1, 2, 3, 4])

In [10]:
kopya_array[:] = 11
kopya_array

array([11, 11, 11, 11, 11])

In [11]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
array_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
#0. satırı gösterelim:
array_2d[0] 

array([1, 2, 3])

In [15]:
#7 elemanını göstermek istersek:
array_2d[2][0]

7

In [17]:
#ya da:
array_2d[2,0]

7

In [18]:
#matris parçalama:
array_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [20]:
array_2d[:2,:2]

array([[1, 2],
       [4, 5]])

In [24]:
array_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [29]:
array_2d[1:,0]

array([4, 7])

In [30]:
#Yalnıca 0. satır ile 2. satırı almak istersek:
array_2d[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [31]:
array_2d[[0,2],[0]]

array([1, 7])

In [32]:
arrayx = np.arange(15)
arrayx

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arrayx < 5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False])

In [34]:
arrayx[arrayx < 7]

array([0, 1, 2, 3, 4, 5, 6])

In [35]:
arrayx[arrayx % 3 == 0]

array([ 0,  3,  6,  9, 12])