# Numpy Array Oluşturma ve Uygulamaları

In [9]:
import numpy as np #numpy ı np şeklinde import ettik.

In [10]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [11]:
#Bir liste ile array oluşturduk.
list1 = [0,1,2,3]          
array = np.array(list1)
array

array([0, 1, 2, 3])

In [12]:
list2 = [10,11,12,13]
kom_list = [list1,list2]
kom_list

[[0, 1, 2, 3], [10, 11, 12, 13]]

In [13]:
#listeleri kombinleyerek array kombini oluşturduk.
kom_array = np.array(kom_list)
kom_array

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [14]:
#array tipini araştırdık.
kom_array.dtype

dtype('int32')

In [15]:
np.array(kom_list,dtype='float')

array([[ 0.,  1.,  2.,  3.],
       [10., 11., 12., 13.]])

In [16]:
#zeros methodu ile 0 matrisleri oluşturulur.
np.zeros((5,2)).astype('int')

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [17]:
#ones methodu ile elemanları 1den oluşan matrisler oluşturulur.
np.ones((7,8)).astype("int")

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [18]:
np.empty((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
#eye ile birim matris oluşturulur.
np.eye(4).astype("int")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(50,100,5)

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [22]:
#50den 100e kadar 5 parçaya böldük.
np.linspace(50,100,6).astype("int")

array([ 50,  60,  70,  80,  90, 100])

In [23]:
import numpy.random as rd

In [24]:
rd

<module 'numpy.random' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [25]:
rd.rand(10)

array([0.83420681, 0.3762565 , 0.49341878, 0.52572939, 0.15314626,
       0.90735381, 0.68769449, 0.09154002, 0.94649274, 0.21039541])

In [26]:
#3 ile 5 arasında 5 elemanlı array olusturduk.
rd.randint(3,5,5) 

array([3, 3, 4, 4, 4])

In [30]:
#Yeniden şekillendirmek için reshape methodu kullanılır.
array1 = rd.randint(0,11,12)
array1.reshape(3,4)

array([[ 4,  0, 10,  7],
       [ 4,  8,  5,  2],
       [ 4,  9,  5,  8]])

In [28]:
array1.reshape(2,6)

array([[ 4,  5, 10,  8,  6,  1],
       [ 3,  0,  5,  8,  4,  0]])

In [29]:
array1.reshape(6,2)

array([[ 4,  5],
       [10,  8],
       [ 6,  1],
       [ 3,  0],
       [ 5,  8],
       [ 4,  0]])