In [1]:
import numpy as np

In [2]:
array = np.arange(6).reshape(3,2)
array

array([[0, 1],
       [2, 3],
       [4, 5]])

In [3]:
array.sum()

15

##### axis=1 olduğunda satr bazlı, axis=0 olduğunda sütun bazlı işlemler yapılır.

In [4]:
#Satırları toplamak için:
array.sum(axis=1)

array([1, 5, 9])

In [5]:
#Sütunları toplamak için:
array.sum(axis=0)

array([6, 9])

In [6]:
array.min()

0

In [7]:
array.min(axis=1)

array([0, 2, 4])

In [8]:
array.argmax()

5

In [9]:
array.argmax(axis=1)

array([1, 1, 1], dtype=int64)

In [10]:
array.argmax(axis=0)

array([2, 2], dtype=int64)

In [11]:
array.mean()

2.5

In [12]:
array.var()

2.9166666666666665

In [13]:
def ortalama_bul(listt):
    return sum(listt) / len(listt)
ortalama_bul([1,2,3])
    

2.0

In [14]:
def varyans_bul(listt):
    toplam = 0
    for i in listt:
        toplam = toplam + ((i - ortalama_bul(listt))**2) / len(listt)
    return toplam
    
varyans_bul([0,1,2,3,4,5])

2.916666666666667

In [15]:
def std_bul(listt):
    std = varyans_bul(listt) ** 0.5
    return std
std_bul([0,1,2,3,4,5])

1.7078251276599332

In [16]:
array.std()

1.707825127659933

In [18]:
array.sort()
array

array([[0, 1],
       [2, 3],
       [4, 5]])