### 1)Numpy modülünü np olarak yükleyelim:


In [1]:
import numpy as np

### 2) lst = [1,2,3] array e çevirelim:


In [3]:
lst = [1,2,3]
np.array(lst)

array([1, 2, 3])

### 3) Elemanları 1 rakamından oluşan 5 birim uzunluğunda bir numpy array oluşturalım:


In [6]:
array = np.ones(5).astype(int)
array

array([1, 1, 1, 1, 1])

### 4) Elemanları 0 rakamından oluşan 2x3 lül bir matris oluşturalım:


In [8]:
array2 = np.zeros(6).reshape(2,3).astype(int)
array2

array([[0, 0, 0],
       [0, 0, 0]])

### 5) Diagonal eksendeki elemanları 4 rakamı, diğerleri 0 olan 3x3 lük bir matris oluşturalım:

In [9]:
array3 = np.array([4,0,0,0,4,0,0,0,4]).reshape(3,3)
array3

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

In [11]:
array4 = np.eye(3).astype(int)
array4 * 4

array([[4, 0, 0],
       [0, 4, 0],
       [0, 0, 4]])

### 6) 10'a kadar olan tam sayılardan oluşan bir array oluşturalım:

In [12]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 7) 12 ile 26 arasında çift sayıları içeren bir array oluşturalım:


In [33]:
array = np.arange(12,26,2)
array


array([12, 14, 16, 18, 20, 22, 24])

### 8) 2 ile 4 arasını 8 eş parçaya bölelim:

In [16]:
np.linspace(2,4,9)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

### 9) numpy.random modülünü rd olarak yükleyelim:

In [17]:
import numpy.random as rd

### 10) numpy modülünün rand methodunu kullanarak 5 elemanlı bir array oluşturalım:

In [18]:
array = rd.rand(5)
array

array([0.13006733, 0.26229368, 0.4923931 , 0.41161818, 0.36432106])

### 11) Değerleri 0 ile 10 tamsayılarından oluşan 3x5 lik bir matris oluşturalım:

In [19]:
array = rd.randint(0,10,(3,5))
array

array([[5, 3, 6, 2, 9],
       [7, 4, 1, 2, 3],
       [6, 1, 5, 4, 7]])

### 12) Oluşturduğumuz arrayin karesini alalım:

In [20]:
array ** 2

array([[25,  9, 36,  4, 81],
       [49, 16,  1,  4,  9],
       [36,  1, 25, 16, 49]], dtype=int32)

### 13) array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

### Verilen arrayin son üç elamanını kopyalayarak yeni bir array oluşturalım, daha sonra yeni oluşturduğumuz arrayin ilk elemanını 99 olarak değiştirelim:

In [23]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
copy_array = a[-3:].copy()
copy_array

array([12, 13, 14])

In [27]:
copy_array[0] = 99
copy_array

array([99, 13, 14])

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 14) Verilen matrisi parçalama işlemleriyle istenilen hale getiriniz:

In [29]:
array2d = np.arange(25).reshape(5,5)
array2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
array2d[1:3,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])